module.exports = [
      {
    company: "Apple Inc.",
    symbol: "AAPL",
    description: "Consumer electronics and software company",
    sector: "Technology",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 212.45,
    marketCap: 3400000000000,
    isActive: true,
  },
  {
    company: "Microsoft",
    symbol: "MSFT",
    description: "Software and cloud computing",
    sector: "Technology",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 510.22,
    marketCap: 3900000000000,
    isActive: true,
  },
  {
    company: "Alphabet",
    symbol: "GOOGL",
    description: "Search engine and cloud services",
    sector: "Technology",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 195.15,
    marketCap: 2500000000000,
    isActive: true,
  },
  {
    company: "Amazon",
    symbol: "AMZN",
    description: "E-commerce and cloud computing",
    sector: "Retail",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 225.8,
    marketCap: 2400000000000,
    isActive: true,
  },
  {
    company: "Tesla",
    symbol: "TSLA",
    description: "Electric vehicle manufacturer",
    sector: "Automobile",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 315.4,
    marketCap: 1000000000000,
    isActive: true,
  },
  {
    company: "NVIDIA",
    symbol: "NVDA",
    description: "Graphics and AI chips",
    sector: "Technology",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 175.4,
    marketCap: 4300000000000,
    isActive: true,
  },
  {
    company: "Meta",
    symbol: "META",
    description: "Social media company",
    sector: "Technology",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 765.2,
    marketCap: 1900000000000,
    isActive: true,
  },
  {
    company: "Netflix",
    symbol: "NFLX",
    description: "Streaming platform",
    sector: "Entertainment",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 1245.3,
    marketCap: 520000000000,
    isActive: true,
  },
  {
    company: "Adobe",
    symbol: "ADBE",
    description: "Creative software",
    sector: "Technology",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 345.5,
    marketCap: 150000000000,
    isActive: true,
  },
  {
    company: "Intel",
    symbol: "INTC",
    description: "Semiconductor manufacturer",
    sector: "Technology",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 25.8,
    marketCap: 120000000000,
    isActive: true,
  },
  {
    company: "AMD",
    symbol: "AMD",
    description: "Semiconductor company",
    sector: "Technology",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 171.4,
    marketCap: 280000000000,
    isActive: true,
  },
  {
    company: "Oracle",
    symbol: "ORCL",
    description: "Database software",
    sector: "Technology",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 242.6,
    marketCap: 680000000000,
    isActive: true,
  },
  {
    company: "Cisco",
    symbol: "CSCO",
    description: "Networking equipment",
    sector: "Technology",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 70.3,
    marketCap: 280000000000,
    isActive: true,
  },
  {
    company: "IBM",
    symbol: "IBM",
    description: "Enterprise technology",
    sector: "Technology",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 290.4,
    marketCap: 270000000000,
    isActive: true,
  },
  {
    company: "Salesforce",
    symbol: "CRM",
    description: "CRM software",
    sector: "Technology",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 252.5,
    marketCap: 240000000000,
    isActive: true,
  },
  {
    company: "PayPal",
    symbol: "PYPL",
    description: "Digital payments",
    sector: "Finance",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 68.2,
    marketCap: 70000000000,
    isActive: true,
  },
  {
    company: "Spotify",
    symbol: "SPOT",
    description: "Music streaming",
    sector: "Entertainment",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 720.5,
    marketCap: 150000000000,
    isActive: true,
  },
  {
    company: "Uber",
    symbol: "UBER",
    description: "Ride sharing",
    sector: "Transportation",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 96.4,
    marketCap: 210000000000,
    isActive: true,
  },
  {
    company: "Airbnb",
    symbol: "ABNB",
    description: "Travel platform",
    sector: "Travel",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 137.8,
    marketCap: 85000000000,
    isActive: true,
  },
  {
    company: "Sony",
    symbol: "SONY",
    description: "Consumer electronics",
    sector: "Technology",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 27.4,
    marketCap: 170000000000,
    isActive: true,
  },
  {
    company: "Samsung Electronics",
    symbol: "SMSN",
    description: "Consumer electronics",
    sector: "Technology",
    exchange: "KRX",
    currency: "USD",
    currentPrice: 57.5,
    marketCap: 320000000000,
    isActive: true,
  },
  {
    company: "Toyota",
    symbol: "TM",
    description: "Automobile manufacturer",
    sector: "Automobile",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 189.4,
    marketCap: 250000000000,
    isActive: true,
  },
  {
    company: "Honda",
    symbol: "HMC",
    description: "Automobile manufacturer",
    sector: "Automobile",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 32.7,
    marketCap: 55000000000,
    isActive: true,
  },
  {
    company: "Ford",
    symbol: "F",
    description: "Automobile manufacturer",
    sector: "Automobile",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 11.6,
    marketCap: 46000000000,
    isActive: true,
  },
  {
    company: "BMW",
    symbol: "BMW",
    description: "Luxury automobile manufacturer",
    sector: "Automobile",
    exchange: "XETRA",
    currency: "USD",
    currentPrice: 96.2,
    marketCap: 67000000000,
    isActive: true,
  },
  {
    company: "Mercedes-Benz",
    symbol: "MBG",
    description: "Luxury automobile manufacturer",
    sector: "Automobile",
    exchange: "XETRA",
    currency: "USD",
    currentPrice: 71.3,
    marketCap: 74000000000,
    isActive: true,
  },
  {
    company: "Shell",
    symbol: "SHEL",
    description: "Energy company",
    sector: "Energy",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 71.6,
    marketCap: 220000000000,
    isActive: true,
  },
  {
    company: "BP",
    symbol: "BP",
    description: "Oil and gas company",
    sector: "Energy",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 35.5,
    marketCap: 97000000000,
    isActive: true,
  },
  {
    company: "Exxon Mobil",
    symbol: "XOM",
    description: "Oil and gas company",
    sector: "Energy",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 114.3,
    marketCap: 520000000000,
    isActive: true,
  },
  {
    company: "Reliance Industries",
    symbol: "RELIANCE",
    description: "Conglomerate",
    sector: "Energy",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 3020.5,
    marketCap: 205000000000,
    isActive: true,
  },
    {
    company: "Tata Consultancy Services",
    symbol: "TCS",
    description: "IT services and consulting",
    sector: "Technology",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 3485.2,
    marketCap: 155000000000,
    isActive: true,
  },
  {
    company: "Infosys",
    symbol: "INFY",
    description: "IT consulting and software",
    sector: "Technology",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 1580.3,
    marketCap: 78000000000,
    isActive: true,
  },
  {
    company: "Wipro",
    symbol: "WIPRO",
    description: "IT services",
    sector: "Technology",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 269.5,
    marketCap: 18000000000,
    isActive: true,
  },
  {
    company: "HCL Technologies",
    symbol: "HCLTECH",
    description: "IT services",
    sector: "Technology",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 1712.8,
    marketCap: 56000000000,
    isActive: true,
  },
  {
    company: "ICICI Bank",
    symbol: "ICICI",
    description: "Private sector bank",
    sector: "Finance",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 1430.2,
    marketCap: 120000000000,
    isActive: true,
  },
  {
    company: "HDFC Bank",
    symbol: "HDFCBANK",
    description: "Private sector bank",
    sector: "Finance",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 2015.4,
    marketCap: 165000000000,
    isActive: true,
  },
  {
    company: "State Bank of India",
    symbol: "SBIN",
    description: "Public sector bank",
    sector: "Finance",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 832.5,
    marketCap: 89000000000,
    isActive: true,
  },
  {
    company: "Axis Bank",
    symbol: "AXISBANK",
    description: "Private sector bank",
    sector: "Finance",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 1189.7,
    marketCap: 42000000000,
    isActive: true,
  },
  {
    company: "Kotak Mahindra Bank",
    symbol: "KOTAKBANK",
    description: "Banking and financial services",
    sector: "Finance",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 1822.1,
    marketCap: 51000000000,
    isActive: true,
  },
  {
    company: "Sun Pharma",
    symbol: "SUNPHARMA",
    description: "Pharmaceutical company",
    sector: "Healthcare",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 1764.8,
    marketCap: 51000000000,
    isActive: true,
  },
  {
    company: "Dr. Reddy's Laboratories",
    symbol: "DRREDDY",
    description: "Pharmaceutical company",
    sector: "Healthcare",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 1328.4,
    marketCap: 24000000000,
    isActive: true,
  },
  {
    company: "Cipla",
    symbol: "CIPLA",
    description: "Pharmaceutical company",
    sector: "Healthcare",
    exchange: "NSE",
    currency: "INR",
    currentPrice: 1548.2,
    marketCap: 19000000000,
    isActive: true,
  },
  {
    company: "Pfizer",
    symbol: "PFE",
    description: "Healthcare company",
    sector: "Healthcare",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 24.8,
    marketCap: 140000000000,
    isActive: true,
  },
  {
    company: "Johnson & Johnson",
    symbol: "JNJ",
    description: "Healthcare products",
    sector: "Healthcare",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 173.6,
    marketCap: 410000000000,
    isActive: true,
  },
  {
    company: "PepsiCo",
    symbol: "PEP",
    description: "Food and beverages",
    sector: "Consumer Goods",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 141.9,
    marketCap: 190000000000,
    isActive: true,
  },
  {
    company: "Coca-Cola",
    symbol: "KO",
    description: "Beverage company",
    sector: "Consumer Goods",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 72.4,
    marketCap: 310000000000,
    isActive: true,
  },
  {
    company: "Nike",
    symbol: "NKE",
    description: "Sportswear company",
    sector: "Retail",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 78.5,
    marketCap: 115000000000,
    isActive: true,
  },
  {
    company: "Adidas",
    symbol: "ADDYY",
    description: "Sportswear company",
    sector: "Retail",
    exchange: "OTC",
    currency: "USD",
    currentPrice: 136.7,
    marketCap: 46000000000,
    isActive: true,
  },
  {
    company: "Walmart",
    symbol: "WMT",
    description: "Retail chain",
    sector: "Retail",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 98.3,
    marketCap: 790000000000,
    isActive: true,
  },
  {
    company: "Costco",
    symbol: "COST",
    description: "Wholesale retailer",
    sector: "Retail",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 972.6,
    marketCap: 430000000000,
    isActive: true,
  },
  {
    company: "Visa",
    symbol: "V",
    description: "Payment technology",
    sector: "Finance",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 361.4,
    marketCap: 720000000000,
    isActive: true,
  },
  {
    company: "Mastercard",
    symbol: "MA",
    description: "Payment technology",
    sector: "Finance",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 589.2,
    marketCap: 520000000000,
    isActive: true,
  },
  {
    company: "American Express",
    symbol: "AXP",
    description: "Financial services",
    sector: "Finance",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 318.8,
    marketCap: 220000000000,
    isActive: true,
  },
  {
    company: "Boeing",
    symbol: "BA",
    description: "Aerospace company",
    sector: "Aerospace",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 242.3,
    marketCap: 185000000000,
    isActive: true,
  },
  {
    company: "Airbus",
    symbol: "AIR",
    description: "Aircraft manufacturer",
    sector: "Aerospace",
    exchange: "EURONEXT",
    currency: "EUR",
    currentPrice: 184.6,
    marketCap: 145000000000,
    isActive: true,
  },
  {
    company: "Disney",
    symbol: "DIS",
    description: "Entertainment company",
    sector: "Entertainment",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 124.7,
    marketCap: 225000000000,
    isActive: true,
  },
  {
    company: "Electronic Arts",
    symbol: "EA",
    description: "Video game company",
    sector: "Entertainment",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 158.2,
    marketCap: 42000000000,
    isActive: true,
  },
  {
    company: "Tencent",
    symbol: "TCEHY",
    description: "Technology and gaming",
    sector: "Technology",
    exchange: "OTC",
    currency: "USD",
    currentPrice: 72.8,
    marketCap: 610000000000,
    isActive: true,
  },
  {
    company: "Alibaba",
    symbol: "BABA",
    description: "E-commerce company",
    sector: "Retail",
    exchange: "NYSE",
    currency: "USD",
    currentPrice: 132.9,
    marketCap: 320000000000,
    isActive: true,
  },
  {
    company: "Qualcomm",
    symbol: "QCOM",
    description: "Semiconductor company",
    sector: "Technology",
    exchange: "NASDAQ",
    currency: "USD",
    currentPrice: 168.5,
    marketCap: 195000000000,
    isActive: true,
  },
];